version: '3.7'

services:
  postgres:
    container_name: pde_postgres
    environment:
      POSTGRES_DB: pde
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    image: postgres:14-alpine
    ports:
      - 5432:5432

networks:
  default:
